[mocap]
camera_frequency = 240.0

[rigid_bodies]
root_name = "Root"
root_stream_id = 1
left_foot_name = "LFoot"
left_foot_stream_id = 2
right_foot_name = "RFoot"
right_foot_stream_id = 3

[networking]
use_multicast = false # Unicast = False / Multicast = True
server_address = "192.168.0.26" # Address in the Motive Software
local_address = "0.0.0.0" # Client Computers IP (Make sure they are on the same subnet)
multicast_address = "239.255.42.99"
command_port = 1510
data_port = 1511

[controller]
controller_path = "~/ros_ws/src/mocap_teleop/mpac_mujoco/mpac_go2/"
interface_subpath = "~/ros_ws/src/mocap_teleop/mpac_mujoco/mpac_go2/atnmy/"

[learning]
gait_classifier_path = "ModelV1.pth"
cbf_model_path       = ""#"kappa_net_3.pth"   # set to "" to disable CBF filter
critic_path          = "kappa_net_9_full.pth"  # set to "" to disable FSM

[logging]
logs_dir = "robot_logs"